version: '3.8'

services:
  web:
    build: .
    image: ativos-pt-web
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # Esta linha diz ao Certbot para verificar se precisa de renovar 
    # o certificado duas vezes por dia, garantindo que nunca expira.
    command: renew --quiet --wait 30s
